### ISSUE TITLE
Remote file deletion on toplevel files fails

### ISSUE THREAD

**Issue by nebulade** [nebulade/surfer#1]
```
16:06:28 [main] /app/code/node_modules/del/index.js:16
16:06:28 [main] 		throw new Error('Cannot delete files/folders outside the current working dir
16:06:28 [main] 		      ^
16:06:28 [main] Error: Cannot delete files/folders outside the current working directory. Can be overriden with the `force` option.
16:06:28 [main]     at safeCheck (/app/code/node_modules/del/index.js:16:9)
16:06:28 [main]     at Immediate.<anonymous> (/app/code/node_modules/del/index.js:42:5)
16:06:28 [main]     at Immediate.immediate._onImmediate (timers.js:418:16)
16:06:28 [main]     at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by LancePorter** [comment]
could you solve it faster please ;)
lol

**Comment by nebulade** [comment]
Fixed now
